lsi: false
safe: true
source: [This is lc github page]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
---
layout: post
title: Blogging Like a Hacker
---
